export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const REGISTRATION_FULFILLED = 'REGISTRATION_FULFILLED';
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED';
