export const TRAIN_NEURAL_NETWROK_FULFILLED = 'TRAIN_NEURAL_NETWROK_FULFILLED';
export const TRAIN_NEURAL_NETWROK_REJECTED = 'TRAIN_NEURAL_NETWROK_REJECTED';


export const SAVE_DESCRIPTION_FULFILLED = 'SAVE_DESCRIPTION_FULFILLED';
export const SAVE_DESCRIPTION_REJECTED = 'SAVE_DESCRIPTION_REJECTED';
