export const TRAIN_NEURAL_NETWROK_FULFILLED = 'TRAIN_NEURAL_NETWROK_FULFILLED';
export const TRAIN_NEURAL_NETWROK_REJECTED = 'TRAIN_NEURAL_NETWROK_REJECTED';

export const TEST_NEURAL_NETWROK_FULFILLED = 'TEST_NEURAL_NETWROK_FULFILLED';
export const TEST_NEURAL_NETWROK_REJECTED = 'TEST_NEURAL_NETWROK_REJECTED';

export const SAVE_DESCRIPTION_FULFILLED = 'SAVE_DESCRIPTION_FULFILLED';
export const SAVE_DESCRIPTION_REJECTED = 'SAVE_DESCRIPTION_REJECTED';

export const FETCH_DESCRIPTIONS_FULFILLED = 'FETCH_DESCRIPTIONS_FULFILLED';
export const FETCH_DESCRIPTIONS_REJECTED = 'FETCH_DESCRIPTIONS_REJECTED';

export const FETCH_SAVED_DESCRIPTIONS_FULFILLED = 'FETCH_SAVED_DESCRIPTIONS_FULFILLED';
export const FETCH_SAVED_DESCRIPTIONS_REJECTED = 'FETCH_SAVED_DESCRIPTIONS_REJECTED';

export const FETCH_DESCRIPTION_BY_ID_FULFILLED = 'FETCH_DESCRIPTION_BY_ID_FULFILLED';
export const FETCH_DESCRIPTION_BY_ID_REJECTED = 'FETCH_DESCRIPTION_BY_ID_REJECTED';

export const FETCH_MODELS_BY_DESC_ID_FULFILLED = 'FETCH_MODELS_BY_DESC_ID_FULFILLED';
export const FETCH_MODELS_BY_DESC_ID_REJECTED = 'FETCH_MODELS_BY_DESC_ID_REJECTED';

export const FETCH_MODEL_BY_ID_FULFILLED = 'FETCH_MODEL_BY_ID_FULFILLED';
export const FETCH_MODEL_BY_ID_REJECTED = 'FETCH_MODEL_BY_ID_REJECTED';

export const RUN_INSTANCE_DESCRIPTION_FULFILLED = 'RUN_INSTANCE_DESCRIPTION_FULFILLED';
export const RUN_INSTANCE_DESCRIPTION_REJECTED = 'RUN_INSTANCE_DESCRIPTION_REJECTED';

export const GENERATE_VINNSL_FULFILLED = 'GENERATE_VINNSL_FULFILLED';
export const GENERATE_VINNSL_REJECTED = 'GENERATE_VINNSL_REJECTED';
