export const FETCH_OPENSTACK_PROJECTS_FULFILLED = 'FETCH_OPENSTACK_PROJECTS_FULFILLED';
export const FETCH_OPENSTACK_PROJECTS_REJECTED = 'FETCH_OPENSTACK_PROJECTS_REJECTED';

export const FETCH_OPENSTACK_PROJECT_BY_ID_FULFILLED = 'FETCH_OPENSTACK_PROJECT_BY_ID_FULFILLED';
export const FETCH_OPENSTACK_PROJECT_BY_ID_REJECTED = 'FETCH_OPENSTACK_PROJECT_BY_ID_REJECTED';

export const FETCH_FLAVOR_FULFILLED = 'FETCH_FLAVOR_FULFILLED';
export const FETCH_FLAVOR_REJECTED = 'FETCH_FLAVOR_REJECTED';

export const FETCH_SERVER_FULFILLED = 'FETCH_SERVER_FULFILLED';
export const FETCH_SERVER_REJECTED = 'FETCH_SERVER_REJECTED';


export const FETCH_MONITOR_FULFILLED = 'FETCH_MONITOR_FULFILLED';
export const FETCH_MONITOR_REJECTED = 'FETCH_MONITOR_REJECTED';
